using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;

namespace TestFactory
{
    public class SystemTestBuilder : IReadOnlyCollection<ITestStep>
    {
        private readonly List<ITestStep> testSteps;

        public SystemTestBuilder()
        {
            this.testSteps = new List<ITestStep>();
        }

        public SystemTestBuilder AddTestStep(ITestStep testStep)
        {
            this.testSteps.Add(testStep);

            return this;
        }

        /// <summary>
        /// Starts the execution of all test steps in this builder.
        /// </summary>
        /// <returns>The test results generated by the test steps.</returns>
        public async Task<ITestResult> Run()
        {
            var testStepResults = new List<ITestStepResult>();
            foreach (var testStep in this.testSteps)
            {
                var stopwatch = new Stopwatch();

                try
                {
                    stopwatch.Start();
                    var testStepResult = await testStep.Run().ConfigureAwait(false);
                    stopwatch.Stop();

                    testStepResults.Add(testStepResult);
                }
                catch (Exception ex)
                {
                    stopwatch.Stop();
                    testStepResults.Add(new TestStepResult(testStep, ex, stopwatch.Elapsed));
                }
            }

            return new TestResult(testStepResults.ToArray());
        }

        public int Count => this.testSteps.Count;

        /// <summary>
        /// Returns the test steps within the builder.
        /// </summary>
        /// <returns>An iterator over the test steps in this builder.</returns>
        public IEnumerator<ITestStep> GetEnumerator() => this.testSteps.GetEnumerator();

        /// <summary>
        /// Explicit interface implementation of <see cref="IEnumerator"/>.
        /// </summary>
        /// <returns>An iterator over the test steps in this builder.</returns>
        IEnumerator IEnumerable.GetEnumerator() => this.GetEnumerator();
    }

    public interface IThenTestStep : ITestStep
    {
    }

    public interface IWhenTestStep : ITestStep
    {
    }

    public interface IGivenTestStep : ITestStep
    {
    }
}
